global:
  resolve_timeout: 10s

route:
  receiver: 'gmail-notifications'
  routes:
    - match:
        severity: 'critical'
      receiver: 'gmail-notifications'

receivers:
- name: 'gmail-notifications'
  email_configs:
    - to: 'km.x.pinki@fosteringlinux.com'
      from: 'pinki.pinki280801@gmail.com'
      smarthost: 'smtp.gmail.com:587'
      auth_username: 'pinki.pinki280801@gmail.com'
      auth_identity: 'pinki.pinki280801@gmail.com'
      auth_password: 'efxujzsvbzbhimqg'
      send_resolved: true

